# Generated by Django 4.2.1 on 2023-06-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prénom', models.CharField(max_length=100)),
                ('groupe', models.CharField(max_length=5)),
                ('photo', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
